ALTER TABLE bundles 
  DROP COLUMN IF EXISTS image,
  DROP COLUMN IF EXISTS discount_percent;

ALTER TABLE bundles 
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS original_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sale_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valid_until TIMESTAMPTZ;

ALTER TABLE bundles 
  ALTER COLUMN original_price DROP DEFAULT,
  ALTER COLUMN sale_price DROP DEFAULT;
